blank_issues_enabled: false
contact_links:
  - name: Report a security issue
    url: https://github.com/kilobyteno/laravel-user-guest-like/security/policy
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug or issue
    url: https://github.com/kilobyteno/laravel-user-guest-like/issues/new
    about: Report a reproducable bug
